In [ ]:
#Import the eikon library (import eikon as ek) and input your unique alphanumeric Eikon app token ('your alphanumeric token').
#These are example Eikon API calls using Starbucks (SBUX.O)

In [1]:
import eikon as ek

In [2]:
ek.set_app_id('your alphanumeric token')

In [3]:
ek.get_timeseries("SBUX.O", fields='*')

SBUX.O         HIGH  CLOSE      LOW   OPEN     COUNT      VOLUME
Date
2017-09-26  55.2200  55.13  54.7950  55.06   33350.0   8021851.0
2017-09-27  55.6000  54.99  54.9600  55.25   41311.0   8671309.0
2017-09-28  55.0800  54.50  54.4500  54.81   41855.0   7607473.0
2017-09-29  54.4700  53.71  53.3600  54.31   66772.0  11944370.0
2017-10-02  54.0400  53.81  53.7500  53.86   43267.0   5955980.0
2017-10-03  54.3400  53.99  53.9000  54.00   38966.0   6137069.0
2017-10-04  54.2000  53.93  53.6900  54.12   35264.0   5569058.0
2017-10-05  54.9700  54.60  53.9200  54.06   45377.0   7994274.0
2017-10-06  55.4500  55.17  54.2450  54.51   60223.0  10576278.0
2017-10-09  55.4900  55.02  54.9600  55.37   40137.0   5822893.0
2017-10-10  55.8492  55.42  55.0800  55.10   46019.0   6573918.0
2017-10-11  55.8000  55.64  55.2600  55.46   44238.0   8881897.0
2017-10-12  56.2700  55.97  55.3090  55.67   45706.0   7234267.0
2017-10-13  56.4300  55.72  55.6100  56.00   40158.0   6231132.0
2017-10-16  55.8000  54.91  54.8900  55.67   42552.0   7256893.0
2017-10-17  55.2300  54.51  54.2900  54.86   67786.0  11227337.0
2017-10-18  55.4300  55.21  54.2200  54.46   49426.0   8299509.0
2017-10-19  55.5423  55.40  54.9000  55.08   39686.0   5720179.0
2017-10-20  55.4000  54.57  54.1750  55.31   67575.0  11741092.0
2017-10-23  54.9350  54.27  54.1800  54.77   51203.0  10111071.0
2017-10-24  54.5600  54.28  54.0200  54.37   46133.0   7818490.0
2017-10-25  54.3900  54.16  53.6600  54.24   53730.0   8281219.0
2017-10-26  55.7500  54.91  54.5000  54.50   65910.0  12211440.0
2017-10-27  55.1200  54.88  54.6800  54.83   58899.0   9922611.0
2017-10-30  55.2300  55.17  54.4000  54.79   45526.0   6430949.0
2017-10-31  55.3050  54.84  54.7000  55.16   49158.0   8857829.0
2017-11-01  55.5900  55.13  54.9400  55.10   52489.0   7189764.0
2017-11-02  55.3900  54.87  54.7700  55.15   84785.0  16879022.0
2017-11-03  56.9400  56.03  54.0500  54.16  157091.0  28773774.0
2017-11-06  56.6900  56.57  55.6300  55.99   72871.0  10835659.0
...             ...    ...      ...    ...       ...         ...
2017-11-20  57.0500  56.81  56.5800  56.67   41405.0   6360086.0
2017-11-21  57.5600  57.26  56.8800  56.96   42995.0   6284259.0
2017-11-22  57.1800  57.14  56.7950  57.07   40011.0   7309073.0
2017-11-24  57.1900  56.80  56.7100  57.19   22089.0   3479177.0
2017-11-27  56.9207  55.91  55.7510  56.83   65804.0  10580296.0
2017-11-28  56.7200  56.66  55.9101  56.03   60237.0   9734431.0
2017-11-29  57.6800  57.51  56.7000  56.71   69009.0  10017914.0
2017-11-30  58.1399  57.82  57.4700  57.64   68303.0  11509224.0
2017-12-01  57.7100  57.32  56.4610  57.50   86714.0  12756391.0
2017-12-04  59.1900  58.76  57.5000  57.54   84729.0  13302050.0
2017-12-05  59.6800  59.34  58.9100  59.25   71409.0  11295644.0
2017-12-06  59.8300  59.28  59.2300  59.38   54369.0   8458198.0
2017-12-07  59.2750  59.14  58.7610  59.12   39972.0   6033792.0
2017-12-08  58.8450  58.61  58.1000  58.52   54076.0   9950491.0
2017-12-11  59.3500  59.07  58.2900  58.39   50159.0  10286560.0
2017-12-12  59.3600  59.27  58.8700  58.99   41589.0   6042917.0
2017-12-13  59.8900  59.49  59.3000  59.44   45124.0   7726299.0
2017-12-14  60.0500  59.70  59.4400  59.73   44691.0   8946111.0
2017-12-15  59.3700  58.29  58.1574  59.25   86490.0  22595018.0
2017-12-18  58.7860  58.03  57.8900  58.44   54491.0   8751620.0
2017-12-19  58.5750  58.01  57.9300  58.13   48452.0   7946435.0
2017-12-20  58.2900  57.73  57.6900  58.22   43470.0   7188717.0
2017-12-21  58.1450  57.58  57.4900  57.94   37179.0   5974474.0
2017-12-22  57.9100  57.30  57.1200  57.57   43596.0   7148723.0
2017-12-26  57.5799  57.14  57.0500  57.27   33710.0   5546208.0
2017-12-27  57.6500  57.27  57.1800  57.19   28385.0   4812173.0
2017-12-28  58.0000  57.81  57.3000  57.47   32273.0   5044505.0
2017-12-29  57.9700  57.43  57.4200  57.74   30698.0   5365646.0
2018-01-02  58.2100  57.63  57.4800  57.95   45129.0   7215978.0
2018-01-03  58.7300  58.71  57.8000  57.93   12694.0   2467018.0

[69 rows x 6 columns]

In [4]:
ek.get_data("SBUX.O", fields = ["CF_HIGH", "CF_LOW"],  parameters=None)

(  Instrument  CF_HIGH  CF_LOW
 0     SBUX.O    58.71    57.8, None)

In [5]:
ek.get_data("SBUX.O", ['TR.Employees', {'TR.GrossProfit':{'params':{'Scale': 6, 'Curn': 'EUR'},'sort_dir':'asc'}}])

(  Instrument  Full-Time Employees  Gross Profit
 0     SBUX.O               277000   11300.92476, None)

In [6]:
ek.get_news_headlines("SBUX.O", date_from='2017-01-05T09:00:00', date_to='2017-04-05T18:00:00')

,versionCreated,text,storyId,sourceCode
2017-04-05 15:46:43,2017-04-05 17:36:22.183,Reuters Insider - Trading at Noon: Stocks clim...,urn:newsml:reuters.com:20170405:nRTV3qwF4z:1,NS:RTRS
2017-04-05 17:09:59,2017-04-05 17:10:02.000,Starbucks Releases 'American Cherry Pie Frappu...,urn:newsml:reuters.com:20170405:nNRA3m96my:1,NS:HUFFPO
2017-04-05 11:43:25,2017-04-05 16:26:11.566,Reuters Insider - JAB to pay $315 per share fo...,urn:newsml:reuters.com:20170405:nRTV8RWQcP:1,NS:CNBC
2017-04-05 14:24:50,2017-04-05 16:11:18.185,Reuters Insider - Faber Report: JAB nabs Paner...,urn:newsml:reuters.com:20170405:nRTV3Xl8DY:1,NS:CNBC
2017-04-05 13:55:16,2017-04-05 16:10:00.644,Reuters Insider - Panera CEO: JAB shares our v...,urn:newsml:reuters.com:20170405:nRTVbN1R0x:1,NS:CNBC
2017-04-05 14:29:33,2017-04-05 14:29:35.003,JAB Holdings Inches Close to Starbucks in Pane...,urn:newsml:reuters.com:20170405:nNRA3m87uc:1,NS:ZACKSC
2017-04-05 10:57:05,2017-04-05 13:12:47.843,"Reuters Insider - U.S. business seeks action, ...",urn:newsml:reuters.com:20170405:nRTV2Y1nDJ:1,NS:RTRS
2017-04-05 11:25:24,2017-04-05 11:28:22.886,"Reuters Insider - U.S. business seeks action, ...",urn:newsml:reuters.com:20170405:nRTV6ZlKMB:1,NS:RTRS
2017-04-05 09:05:05,2017-04-05 09:05:17.003,Starbucks Adds New Toasted Coconut Cold Brew t...,urn:newsml:reuters.com:20170405:nNRA3m66r3:1,NS:ENPNWS
2017-04-04 22:10:29,2017-04-04 22:15:04.532,Reuters Insider - JAB Holding in advanced talk...,urn:newsml:reuters.com:20170404:nRTV2NnMcf:1,NS:CNBC